#!/bin/bash

SCRIPT_DIR="$(dirname "$(realpath "$0")")"
if [[ "$SCRIPT_DIR" != /spfs* ]]; then
    SCRIPT_DIR="$(dirname "$(realpath "$0")")"
    PROJ_DIR="$(dirname $SCRIPT_DIR)"
    PROJ_PARENT_DIR="$(dirname $PROJ_DIR)"
    export PYTHONPATH="$PROJ_PARENT_DIR:$PYTHONPATH"
    echo $PYTHONPATH
    export RV_SUPPORT_PATH=$PROJ_DIR/local_install/lib/open_rv
    export ITVIEW5_CORE_PLUGINS_CONFIG="$PROJ_PARENT_DIR/itview5_plugins/open_itview5_plugins.cfg"
    echo $ITVIEW5_CORE_PLUGINS_CONFIG
fi

exec "$RV_HOME/bin/rv" -flags ModeManagerPreload=ocio_source_setup "$@"
